name: eutc build

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: docker://drvspw/eutc-build:gh

    steps:
    - uses: actions/checkout@v1

    - name: Compile
      run: rebar3 xref

    - name: Run tests
      run: rebar3 eunit

  release:
    needs: build

    runs-on: ubuntu-latest

    if: endsWith(github.ref, 'refs/heads/master')

    container: docker://circleci/golang

    steps:
    - uses: actions/checkout@v1

    - name: Push Tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token

      run: |
        go get github.com/tcnksm/ghr
        VERSION=$(./.package.sh version)
        REPO=$(./.package.sh repo)
        OWNER=$(./.package.sh owner)
        ghr \
            -t ${GITHUB_TOKEN} \
            -u ${OWNER} \
            -r ${REPO} \
            -c ${GITHUB_SHA} \
            -delete \
            ${VERSION} ./README.md
