name: eutc build

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: docker://drvspw/eutc-build

    steps:
      - uses: actions/checkout@v1
      
      - name: Build eutc
        run: rebar3 xref

      - name: Test eutc
        run: rebar3 eunit
      
  release:
    runs-on: ubuntu-latest
    needs: build
    if: endsWith(github.ref, "refs/head/master")

    steps:
      - name: Checkout
      - uses: actions/checkout@v1
        
      - name: Release Version
        run: |
          echo "::set-env name=VERSION::$(./.package.sh version)"
      
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.0
        with:
          name: $VERSION
